# Generated by Django 5.0.2 on 2024-02-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uname', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
                ('cpassword', models.CharField(max_length=15)),
            ],
        ),
    ]
